[package]
name = "diffilate"
version = "0.5.0"
edition = "2021"
authors = ["arsenius_gen <arsenius.gen@proton.me>"]
description = "Saves diffirence between files in optimized way"
license = "MIT"

[dependencies]
